---
# One account per keystone user
# Multiple accounts can be made per config file

# Name here not used, will simply iterate through list
# Name will be printed when running program
- user:
        name: 'arya'
        password: 'joffrey_sucks'
        email: None


  projects:
    # Name here not used, will simply iterate through list
    # Name will be printed when running program
    - name: 'winterfell'
      description: 'winter is coming'
      role: '_member_'

# Flavors will be made public for everyone
  flavors:
    - name: 'biggie smalls'
      ram: 4096
      vcpus: 4
      disk: 0

  nova_quotas:
    # Will find tenant by name
    # Any valid arg can be used here
    # All keys (besides tenant name) passed directly into the query

    - tenant_name: 'winterfell'
      instances: 20

  cinder_quotas:
    # Will find tenant by name
    # Any valid arg can be used here
    # All keys (besides tenant name) passed directly into the query

    - tenant_name: 'winterfell'
      volumes: 20

  security_groups:
    - name: 'ssh port'
      description: Simply ssh port group
      tenant_name: 'winterfell'
      rules:
        - from_port: 22
          to_port: 22
          ip_protocol: 'tcp'
          cidr: '0.0.0.0/0'

  keypairs:
    - name: 'my-public-key'
      file: '/home/user/.ssh/id_rsa.pub'

  source_files:
    - tenant_name: 'winterfell'
      file: '/home/user/arya_openrc.sh'

  images:
    - tenant_name: 'winterfell'
      # Whether 'file' (uploaded from local file) or 'copy_from' (copied from URL) can be set
      copy_from: 'http://www.change-me.org/debian-7.3.img'
      # file: '/home/user/images/debian-7.3.img'
      container_format: 'bare'
      disk_format: 'qcow2'
      is_public: False
