---
# Place list of actions to complete, they will be done in order
# Each action will need at least one valid section
# Sections in each action will be done in a random order
# Each section can have a list of items that will be created in order


- user:
      name: 'arya'
      password: 'joffrey_sucks'
      email: None
  user:
     name: 'gentry'
     password: 'mah_helm'
     email: None

- project:
      name: 'winterfell'
      description: 'winter is coming'
      # Add user with roles
      role: 'admin'
      user: 'arya'

- flavor:
      name: 'kraken'
      ram: 4096
      vcpus: 4
      disk: 0

- nova_quota:
    # Will find tenant by name
    # Any valid arg can be used here
    # All keys (besides tenant name) passed directly into the query
      tenant_name: 'winterfell'
      instances: 20
      ram: 5120000
      cores: 80

  cinder_quota:
    # Will find tenant by name
    # Any valid arg can be used here
    # All keys (besides tenant name) passed directly into the query

      tenant_name: 'winterfell'
      volumes: 20
      gigabytes: 1000000


  security_group:
      name: 'ssh port'
      description: Simply ssh port group
      rules:
        - from_port: 22
          to_port: 22
          ip_protocol: 'tcp'
          cidr: '0.0.0.0/0'

- keypair:
      name: 'my-public-key'
      file: '/home/user/.ssh/id_rsa.pub'
  os_username: 'arya'
  os_password: 'joffrey_sucks'
  os_tenant_name: 'winterfell'

- network :
      name: 'the north'
      tenant_name: 'winterfell'
      shared: True

- subnet:
      name: 'moat cailin'
      network: 'the north'
      tenant_name: 'winterfell'
      cidr: '192.168.0.0/24'
      ip_version: '4'

- router:
      name: 'the kingsroad'
      tenant_name: 'winterfell'
      external_network: 'external'
      internal_subnet: 'moat cailin'

- source_file:
      tenant_name: 'winterfell'
      file: '/home/user/arya_openrc.sh'
      user: 'arya'

- image:
      # Whether 'file' (uploaded from local file) or 'copy_from' (copied from URL) can be set
      name: 'Debian 7.3'
      copy_from: 'http://www.change-me.org/debian-7.3.img'
      # file: '/home/user/images/debian-7.3.img'
      container_format: 'bare'
      disk_format: 'qcow2'
      is_public: False
      # Wait until image is active
      wait: True
      timeout: 1200

- volume:
      name: 'weirwood'
      size: 20
      wait: True
      timeout: 3600

- server:
      name: 'ice'
      flavor_name: 'kraken'
      image_name: 'Debian 7.3'
      wait: True
      timeout: 1200
